replicaCount: 1

image:
  repository: price-manager-app
  tag: 0.0.0-SNAPSHOT
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 80

httpRoute:
  enabled: false
  parentRefs: []
  hostnames: []
  matches:
    - path:
        type: PathPrefix
        value: /

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

env:
  baseUrl: "http://service.priceprovider.local/"
  oidcIssuerUri: "http://keycloak.priceprovider.local/realms/priceprovider"
  oidcRequireHttps: "false"

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 30
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10
