apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-dev-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/commerce-stack-solutions/priceprovider.git'
    targetRevision: master
    path: deployment/k8s/argocd
    directory:
      recurse: false
      include: 'local-dev-applications.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
